environment:
  fast_finish: true

  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VSPATH: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    BS: cmake
    CMAKE_GENERATOR: '"Visual Studio 14 2015"'
    VS_SHORT_NAME: vs14
    BOOST_INCLUDE_DIR: C:/Libraries/boost_1_62_0
    BOOST_LIBRARY_DIR: C:/Libraries/boost_1_62_0/lib64-msvc-14.0

  #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  #  VSPATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build
  #  BS: cmake
  #  CMAKE_GENERATOR: '"Visual Studio 15 2017"'
  #  VS_SHORT_NAME: vs15
  #  BOOST_INCLUDE_DIR: C:/Libraries/boost_1_64_0
  #  BOOST_LIBRARY_DIR: C:/Libraries/boost_1_64_0/lib64-msvc-15.0

platform: x64

configuration:
  - Debug
  - Release

cache:
  # cmake
  #- C:\cmake-3.7.2-win32-x86
  # CAF
  - C:\lib\%VS_SHORT_NAME%\actor-framework\libcaf_core\caf
  - C:\lib\%VS_SHORT_NAME%\actor-framework\build\lib\%CONFIGURATION%
  - C:\lib\%VS_SHORT_NAME%\restbed\source
  - C:\lib\%VS_SHORT_NAME%\restbed\build\%CONFIGURATION%

# prepare dependencies
install:
  # submodules
  # - git clone https://github.com/DePizzottri/delta-enabled-crdts.git C:\projects\nomadb\libs\delta-enabled-crdts
  - git submodule update --init --recursive
  # cmake
  #- ps: |
  #    if (![IO.File]::Exists("C:\cmake-3.8.2-win64-x64\bin\cmake.exe")) {
  #      pushd c:\
  #      Start-FileDownload 'https://cmake.org/files/v3.8/cmake-3.8.2-win64-x64.zip'
  #      7z x -y cmake-3.8.2-win64-x64.zip
  #      popd
  #    }
  - call "%VSPATH%"\vcvarsall %PLATFORM%
  #- set PATH=C:\cmake-3.8.2-win64-x64\bin;%PATH%;
  # prepare 
  - if not exist C:\lib\%VS_SHORT_NAME% (mkdir C:\lib\%VS_SHORT_NAME%)
  - cd C:\lib\%VS_SHORT_NAME%
  # CAF
  - call %APPVEYOR_BUILD_FOLDER%/ci/build_CAF.bat
  # restbed
  - call %APPVEYOR_BUILD_FOLDER%/ci/build_restbed.bat

  #end
  # - popd
  - echo "Done preparing dependencies"

build_script:
  - msbuild "%APPVEYOR_BUILD_FOLDER%/msvc/NomaDB.sln" /p:Configuration=%CONFIGURATION% /p:Platform=%PLATFORM% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
  - call "%APPVEYOR_BUILD_FOLDER%/msvc/%PLATFORM%/%CONFIGURATION%/test.exe"