environment:
  fast_finish: true

  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VSPATH: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    BS: cmake
    CMAKE_GENERATOR: '"Visual Studio 14 2015"'

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VSPATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build
    BS: cmake
    CMAKE_GENERATOR: '"Visual Studio 15 2017"'

platform: x64

configuration:
  - Debug
  - Release

cache:
  # cmake
  - C:\cmake-3.7.2-win32-x86
  # CAF
  - C:\lib\actor-framework\libcaf_core\caf
  - C:\lib\actor-framework\build\lib\%CONFIGURATION%
  - C:\lib\restbed\build\%CONFIGURATION%

# prepare dependencies
install:
  # cmake 
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.7.2-win32-x86\bin\cmake.exe")) {
        pushd c:\
        Start-FileDownload 'https://cmake.org/files/v3.7/cmake-3.7.2-win32-x86.zip'
        7z x -y cmake-3.7.2-win32-x86.zip
        popd
      }
  - call "%VSPATH%"\vcvarsall %PLATFORM%
  - set PATH=C:\cmake-3.7.2-win32-x86\bin;%PATH%;
  # prepare 
  - if not exist c:\lib (mkdir c:\lib)
  - cd c:\lib
  # CAF
  - call %APPVEYOR_BUILD_FOLDER%/ci/build_CAF.bat
  - dir
  # restbed
  - call %APPVEYOR_BUILD_FOLDER%/ci/build_restbed.bat

  #end
  # - popd
  - echo "Done preparing dependencies"
  
build: off  